a=input("Digite algo :")
print("O tipo primitivo desse valor é ", type(a))
print("Só tem espaços?", a.isspace())
print("É um número?", a.isnumeric())
print("É alfabético?", a.isalpha())
print("É alfanumérico?", a.isalnum())
print("está em maisculas?", a.isupper())
print("está em minusculas?", a.islower())
print("está em capitalizado?", a.istitle())
